feat: extend the behavior of clipping for the allowDataOverflow property
recharts/recharts pull request #2488
Opened 2021-03-09 17:45 UTC by tylerben

### Overview

This PR covers two main updates related to the clipping behavior associated with the `allowDataOverflow` prop that is available on the `XAxis` and `YAxis` components.
- ensuring that the clip path generated when setting the `allowDataOverflow` prop to true on an axis only clips the axis it was called on (calling this the "Independent Axis Clipping")
- adding the ability to specify whether dots should be clipped by the clip path when the `allowDataOverflow` prop is set to true (calling this "Dot Clipping Configuration")

**Related issues and PRs**
- #2304 
- https://github.com/recharts/recharts/pull/1237
- https://github.com/recharts/recharts/pull/1571

### Independent Axis Clipping
We noticed that the clip path does not take into consideration which axis the `allowDataOverflow` prop is attached to so if the prop is set to true on either axis, the clip path impacts both axes. This PR expands the existing functionality to ensure that the clip path only impacts the axis where the `allowDataOverflow` is set to true. With the updates, if you want the clip path to apply to both a y and x axis, you would need to set `allowDataOverflow` to true on both components.

This update was made to the following cartesian components:
- Area
- Bar
- Line
- Scatter

**Screenshots**

Previous behavior where `allowDataOverflow` prop does not respect the axis it is set on. `allowDataOverflow` is set to true on the `YAxis` and false on the `XAxis` component but the chart is clipped on both axes anyways.

![image](https://user-images.githubusercontent.com/16169752/110512138-cce81900-80b9-11eb-98c4-b142817e4ad0.png)

Updated behavior where only the `yAxis` clipping is in play like it should be for the above configuration.

![image](https://user-images.githubusercontent.com/16169752/110512532-1fc1d080-80ba-11eb-99df-c46100d14d10.png)

### Dot Clipping Configuration

Currently, if `allowDataOverflow` is set to true, dots are clipped at the axis bounds. We have a use case (similar to #2304) where we wanted the dots to to be visible and not cut off by the clip path. We solved this by adding support for a `clipDot` property that can be used to easily clip or not clip the dot (defaults to true aka clip the dot). If the user has specified that they would not like to clip the dot, a second clip path is used that offsets and extends the clip path using the chart width/height and radius/stroke width.

Here is an example

```js
<Area dataKey="count" fill="#15CC09" dot={{ r: 3, strokeWidth: 2, clipDot: false }} />
```

This update was made to the following cartesian components:
- Area
- Line

#### Screenshots

Existing behavior with `allowDataOverflow` set to true.

![image](https://user-images.githubusercontent.com/16169752/110513466-19802400-80bb-11eb-8c7a-fc01216b788d.png)

Updated behavior with the ability to opt out of dot clipping.
![image](https://user-images.githubusercontent.com/16169752/110513558-361c5c00-80bb-11eb-904e-99bd09c6ef77.png)

2021-07-21 21:06 UTC, semoal approved these changes

2021-11-22 20:56 UTC, abartolo commented
Any update if this will be merged soon?

2021-11-22 21:00 UTC, abartolo commented
disregard my comment above - my clipping was resolved by adding `margin` to the <LineChart />


```
      <LineChart
        data={data}
        margin={{
          top: 30,
          right: 30,
        }}
      >

```

2022-03-17 06:04 UTC, jufemaiz commented
Given the PR is a year old and has an approval from a member of the recharts team it's still worthwhile asking:

1. Will this be merged soon?
2. If not, what is the blocker for merging?

2022-04-29 01:44 UTC, Fullchee commented
I am willing to contribute as well but I'm not sure what there is left to do

2022-04-29 13:00 UTC, tylerben commented
As the author of the PR would love to see this get merged in as well. Are there any blockers for merging this @semoal?

2022-05-17 01:31 UTC, jufemaiz commented
> Given the PR is a year old and has an approval from a member of the recharts team it's still worthwhile asking:
> 
> 1. Will this be merged soon?
> 2. If not, what is the blocker for merging?

Would some of the last few recent committers please provide some guidance?

* @jmfrancois 
* @dillonreedy
* @arcthur
* @xile611 

Thanks!

2022-12-14 04:24 UTC, ckifer requested changes
This project doesn't use yarn, please do your install with npm.

If we can avoid the `DotProps` cast and remove the `yarn.lock` I think we're good.

2022-12-14 04:24 UTC, ckifer commented on src/cartesian/Area.tsx
> +    const { clipDot = true } = dot as DotProps;
any way we can avoid casting this? Can we create a typeguard?

add to `DotProps` a 
```
...
propsType: 'dot';
...
```

then

`const isDotProps = (dot: AreaDot): dot is DotProps => 'propsType' in dot && dot.propsType === 'dot'`?

2023-05-23 22:44 UTC, ckifer commented
Made a new PR for this since it hasn't been active or responded to. See https://github.com/recharts/recharts/pull/3602

2023-05-30 03:07 UTC, ckifer commented
Going to close this as stale in favor of linked PR above - this is still linked to that issue for the details that are provided here

2023-05-30 03:07 UTC, closed without merging

2023-05-31 17:57 UTC, ckifer commented
merged in #3602

2023-06-15 06:04 UTC, ckifer commented
released in 2.7