test(JestMigration): convert Area
recharts/recharts pull request #3180
Opened 2023-01-16 03:13 UTC by Yilun-Sun

## Description

Refactor `test/specs/cartesian/AreaSpec.js` -> `test-jest/cartesian/Area.spec.ts`

## Related Issue

#3158 

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2023-01-16 07:46 UTC, nikolasrieble commented on test-jest/cartesian/Area.spec.tsx
> +    expect(container.querySelectorAll('.customized-dot')).toHaveLength(data.length);
Nit: You could consider to follow best practice guide and query via `screen` as opposed to container. 

https://stackoverflow.com/questions/61482418/react-testing-library-screen-vs-render-queries

2023-01-16 07:47 UTC, nikolasrieble commented on test-jest/cartesian/Area.spec.tsx
> +  const data: any = [
It would be nice to not use any, just to set an example.

2023-01-16 07:47 UTC, nikolasrieble approved these changes
Looks good! I left two minor nits you could consider.

2023-01-16 12:27 UTC, nikolasrieble approved these changes
🚀

2023-01-17 17:26 UTC, ckifer requested changes
LGTM 🚀 .  One thing @Yilun-Sun could you squash this into 2 commits? One commit specifically for the change to Area props and one for the tests. Then I'll rebase merge so that the commit history is preserved nicely for the two different changes

2023-01-18 14:10 UTC, ckifer commented
@Yilun-Sun thanks! Merged the other PR but looks like there's still 5 commits here with conflicts. You'll have to reset to master, pull down the area props change, then commit the test changes in 1 commit rather than 5

2023-01-19 03:36 UTC, ckifer approved these changes

2023-01-19 03:36 UTC, merged