Convert ReferenceAreaSpec.js -> ReferenceArea.spec.tsx
recharts/recharts pull request #3205
Opened 2023-01-21 02:02 UTC by proke03

## Description
Migrate ReferenceAreaSpec.js -> ReferenceArea.spec.tsx

## Related Issue
#3189

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-01-21 19:26 UTC, nikolasrieble commented on test-jest/cartesian/ReferenceArea.spec.tsx
> +    const { container } = render(
```suggestion
    render(
```

Please do not disable eslint, instead try to fix it.

2023-01-21 19:27 UTC, nikolasrieble commented on test-jest/cartesian/ReferenceArea.spec.tsx
> +    const { container } = render(
In this case you use the screen, and the container is unused.

2023-01-21 19:27 UTC, nikolasrieble requested changes
Please do not ignore eslint but instead follow the setup.

2023-01-22 07:29 UTC, ckifer approved these changes
LGTM but lets try to avoid using `any` if at all possible

2023-01-22 07:29 UTC, ckifer commented on test-jest/cartesian/ReferenceArea.spec.tsx
> +    const renderLabel = (props: any) => {
nit: any way we can actually type these props?

Fine for the sake of the test migration though I'd like to avoid the use of `any` where possible

2023-01-22 07:29 UTC, ckifer commented on test-jest/cartesian/ReferenceArea.spec.tsx
> +    const Label = ({ text, ...props }: { text: any }) => <text {...props}>{text}</text>;
nit: same as above - `text` should be a string here I think

2023-01-22 07:29 UTC, merged