Storybook: add reference line stories
recharts/recharts pull request #3474
Opened 2023-03-22 10:50 UTC by Yilun-Sun

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-03-22 14:19 UTC, nikolasrieble commented on storybook/stories/API/cartesian/ReferenceLine.stories.tsx
> +    strokeDasharray: '3 3',
As the parameters only includes the segment, you could instead just hardcode these values in the rendering. 
Also, ideally, all stories only deviate from the default in one aspect - the control.

2023-03-22 14:19 UTC, nikolasrieble commented on storybook/stories/API/cartesian/ReferenceLine.stories.tsx
> +    expect(await findByText('1800')).toBeInTheDocument();
Nice!

2023-03-22 14:20 UTC, nikolasrieble commented on storybook/stories/API/cartesian/ReferenceLine.stories.tsx
> +  },
Should we possibly reuse the existing documentation instead of redefining it here? i.e. maybe export the style props separately from `props/Style.ts`

2023-03-22 14:21 UTC, nikolasrieble approved these changes
A few question, but looks good to go!

2023-03-26 21:23 UTC, ckifer requested changes
Nice, just one minor thing.
I would just merge and follow up but probably better to get it now to not forget

2023-03-26 21:23 UTC, ckifer commented on storybook/stories/API/cartesian/ReferenceLine.stories.tsx
> +     * assert that when ifOverflow="extendDomain" 1900 becomes the new domain y-max.
comment says 1900 but the find is 1800, can we update one or the other?

2023-03-31 05:25 UTC, ckifer approved these changes
Awesome, thanks!

2023-03-31 05:33 UTC, merged