add: ResponsiveContainer story
recharts/recharts pull request #3603
Opened 2023-05-24 13:27 UTC by akamfoad

## Description
Add ResponsiveContainer story and a simple example of how to use it.

## Related Issue

Follow up of #3596

## Motivation and Context

Document ResponsiveContainer and how its used.

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [X] Documentation & Storybook
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-05-24 18:51 UTC, ckifer requested changes
Few nits and one change requested - we want to follow the linked pattern I think as opposed to strictly using ArgTypes

2023-05-24 18:51 UTC, ckifer commented on storybook/stories/API/ResponsiveContainer.mdx
> +frameworks do, then initially on the Browser, the chart will not be shown until after hydration.
Nit: "as most JavaScript frameworks do" can probably be removed. I would still say most JavaScript frameworks/libraries render on the client as opposed to the server. Can just call out SSR but not be specific

2023-05-24 18:51 UTC, ckifer commented on storybook/stories/API/ResponsiveContainer.mdx
> +> [content layout shift](https://web.dev/cls) that can be annoying for your users.
nit nit nit: wording, change `that can` to `which could`?

2023-05-24 18:51 UTC, ckifer commented on storybook/stories/API/ResponsiveContainer.mdx
> +The ResponsiveContainer can be used to render all types of charts
nit nit: wording, `all types of charts` -> `recharts charts as well as any child that needs to know the dimensions of its parent container`

2023-05-24 18:51 UTC, ckifer commented on storybook/stories/API/ResponsiveContainer.mdx
> +<ArgTypes of={ResponsiveContainerStories} sort={'requiredFirst'} />
We're following a bit of a slightly different pattern now, can you follow this example?

https://github.com/recharts/recharts/blob/master/storybook/stories/API/cartesian/Area.mdx?plain=1#L6-L22

2023-05-25 07:30 UTC, akamfoad commented
@ckifer  Thanks for the suggestions, I think its ready for another round.

2023-05-30 03:05 UTC, ckifer approved these changes
LGTM, I would just say that in general this is a lot of text. Text tends to become outdated over time so if we make changes to behavior we need to make sure we read the docs back to ourselves and ensure the things we say here are still true.

2023-05-30 16:53 UTC, merged