Fix ResponsiveContainer
recharts/recharts pull request #3921
Opened 2023-10-30 18:30 UTC by HHongSeungWoo

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a storybook story or extended an existing story to show my changes
- [x] All new and existing tests passed.

2023-10-30 20:00 UTC, ckifer requested changes
Curious what happens when multiple charts are added in one container. Even if that isn't supported, it still shouldn't break with a variable access issue like this might

2023-10-31 06:53 UTC, HHongSeungWoo commented on src/component/ResponsiveContainer.tsx
> +      const isCharts = getDisplayName(children.type).endsWith('Chart');
Even without this change, `ResponsiveContainer` has only allowed a single child.
I also don't want to use `getDisplayName`, but I don't have any other ideas at the moment

2023-10-31 07:31 UTC, HHongSeungWoo commented
I have made changes to accept any type of children

2023-11-01 06:36 UTC, ckifer approved these changes
Unfortunately we kind of end up making this component more complex, but I think the benefits are worth it for sure - lets see what this looks like in chromatic

edit: looked good to me

2023-11-01 06:37 UTC, merged

2024-05-17 23:08 UTC, ckifer commented
@HHongSeungWoo do you remember what this fixed?