feat: Add the dataKey type to legend props
recharts/recharts pull request #4035
Opened 2024-01-03 00:55 UTC by HHongSeungWoo

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a storybook story or extended an existing story to show my changes
- [x] All new and existing tests passed.

2024-01-03 01:01 UTC, ckifer requested changes
build is failing

2024-01-03 21:14 UTC, ckifer approved these changes

2024-01-03 21:15 UTC, ckifer commented
Thanks!

2024-01-03 21:15 UTC, merged

2024-01-27 11:23 UTC, nikolasrieble commented
Feedback as I am preparing the release: As this is a TS only change, i am considering this a fix, and not a feature. Strictly speaking it already worked.