Remove RadialBar branch from getItemByXY
recharts/recharts pull request #4411
Opened 2024-04-10 11:10 UTC by PavelVanecek

## Description

it's unreachable code for two reasons:

1. RadialBar does not have `activeBar` prop
2. Even if I go ahead and add the `activeBar` prop (it doesn't do anything) and then silence it with typescript, it still doesn't reach this branch because activeTooltipIndex defaults to zero

Same story as Bar before: https://github.com/recharts/recharts/pull/4408

## Related Issue

https://github.com/recharts/recharts/discussions/3717

## Motivation and Context

Remove dead code

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a storybook story or extended an existing story to show my changes

2024-04-10 15:50 UTC, ckifer commented
`RadialBar` has an `activeShape` prop

2024-04-10 16:02 UTC, ckifer requested changes
Looks good, we could probably rename the function though

2024-04-11 00:02 UTC, PavelVanecek commented on src/chart/generateCategoricalChart.tsx
> -    public getItemByXY(chartXY: { x: number; y: number }) {
Renamed. I am going to remove this whole function eventually though.

2024-04-11 00:03 UTC, PavelVanecek commented
I rebased and tested with `activeShape` too, thx @ckifer for bringing that up. All looks the same (activeShape boolean is not doing anything on 3.x and continues doing nothing here.)

2024-04-11 00:05 UTC, ckifer commented
I mean it's not doing nothing, but it does not reach the removed code path

2024-04-11 00:12 UTC, ckifer approved these changes

2024-04-11 00:12 UTC, merged